from enum import Enum


class TradeStage(str, Enum):
    INSPECTION = "INSPECTION"
    DEPRECIATION = "DEPRECIATION"
    DELIVERY = "DELIVERY"
    REMITTANCE = "REMITTANCE"
    SETTLEMENT = "SETTLEMENT"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class InspectionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"


class DepreciationStatus(str, Enum):
    PROPOSAL_REQUIRED = "PROPOSAL_REQUIRED"
    SELLER_REVIEW = "SELLER_REVIEW"
    RENEGOTIATION_REQUESTED = "RENEGOTIATION_REQUESTED"
    AGREED = "AGREED"


class DeliveryStatus(str, Enum):
    WAITING_SCHEDULE = "WAITING_SCHEDULE"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class RemittanceStatus(str, Enum):
    WAITING = "WAITING"
    SUBMITTED = "SUBMITTED"
    CONFIRMED = "CONFIRMED"


class SettlementStatus(str, Enum):
    WAITING = "WAITING"
    COMPLETED = "COMPLETED"
